version: '3.8'
services:
  db01:
    build: 
      context: ./Docker-files/db
    image: employeedb
    container_name: db01
    ports:
      - "3306:3306"
    volumes:
      - db01data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root1234

  app01:
    build: 
      context: ./Docker-files/app
    image: employeeapp
    container_name: app01
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db01
    
  client:
    build: 
      context: ../Front_end_EmployeeManagement
    image: client
    container_name: client
    ports:
      - "4200:4200"
    depends_on:
      - app01
    

volumes:
  db01data: {}

  
  
