version: '3.8'
services:
  db01:
    build: 
      context: ./Docker-files/db
    container_name: db01
    ports:
      - "3306:3306"
    volumes:
      - db01data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root123

  app01:
    build: 
      context: ./Docker-files/app
  container_name: app01
  ports:
    - "8080:8080"
  volumes:
    - app01data:/usr/local/tomcat/webapps

volumes:
  db01data: {}
  app01data: {}
  
  
